// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string
          name: string
          country: string
          created_at: string | null
        }
        Insert: {
          id?: string
          name: string
          country: string
          created_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          country?: string
          created_at?: string | null
        }
      }
      plans: {
        Row: {
          id: string
          coverage_json: Json
          coverage_text: string
          created_at: string | null
        }
        Insert: {
          id?: string
          coverage_json: Json
          coverage_text: string
          created_at?: string | null
        }
        Update: {
          id?: string
          coverage_json?: Json
          coverage_text?: string
          created_at?: string | null
        }
      }
      users: {
        Row: {
          id: string
          auth_user_id: string | null
          company_id: string
          plan_id: string
          full_name: string
          phone: string | null
          activation_code_hash: string | null
          activation_code_created_at: string | null
          activated_at: string | null
          created_at: string | null
          gender: string | null
          age: number | null
          city: string | null
        }
        Insert: {
          id?: string
          auth_user_id?: string | null
          company_id: string
          plan_id: string
          full_name: string
          phone?: string | null
          activation_code_hash?: string | null
          activation_code_created_at?: string | null
          activated_at?: string | null
          created_at?: string | null
          gender?: string | null
          age?: number | null
          city?: string | null
        }
        Update: {
          id?: string
          auth_user_id?: string | null
          company_id?: string
          plan_id?: string
          full_name?: string
          phone?: string | null
          activation_code_hash?: string | null
          activation_code_created_at?: string | null
          activated_at?: string | null
          created_at?: string | null
          gender?: string | null
          age?: number | null
          city?: string | null
        }
      }
      chat_messages: {
        Row: {
          id: string
          user_id: string
          role: 'user' | 'ai'
          content: string
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          role: 'user' | 'ai'
          content: string
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          role?: 'user' | 'ai'
          content?: string
          created_at?: string | null
        }
      }
      chat_summaries: {
        Row: {
          id: string
          user_id: string
          summary_text: string
          updated_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          summary_text?: string
          updated_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          summary_text?: string
          updated_at?: string | null
        }
      }
      support_requests: {
        Row: {
          id: string
          user_id: string
          user_phone: string
          user_name: string
          company_name: string
          company_country: string
          plan_coverage_summary: string | null
          chat_summary: string | null
          recent_messages: Json | null
          status: 'pending' | 'in_progress' | 'waiting_for_customer' | 'waiting_for_team' | 'resolved' | 'cancelled'
          requested_at: string | null
          resolved_at: string | null
          notes: string | null
          gender: string | null
          age: number | null
          city: string | null
          current_status: 'pending' | 'reviewing_case' | 'contacting_customer' | 'working_on_solution' | 'discussion_with_team' | 'waiting_for_approval' | 'preparing_response' | 'resolved' | 'cancelled'
          status_message: string | null
          assigned_to: string | null
          internal_notes: string | null
          customer_notes: string | null
          status_updated_at: string | null
          last_activity_at: string | null
          status_history: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          user_phone: string
          user_name: string
          company_name: string
          company_country: string
          plan_coverage_summary?: string | null
          chat_summary?: string | null
          recent_messages?: Json | null
          status?: 'pending' | 'in_progress' | 'waiting_for_customer' | 'waiting_for_team' | 'resolved' | 'cancelled'
          requested_at?: string | null
          resolved_at?: string | null
          notes?: string | null
          gender?: string | null
          age?: number | null
          city?: string | null
          current_status?: 'pending' | 'reviewing_case' | 'contacting_customer' | 'working_on_solution' | 'discussion_with_team' | 'waiting_for_approval' | 'preparing_response' | 'resolved' | 'cancelled'
          status_message?: string | null
          assigned_to?: string | null
          internal_notes?: string | null
          customer_notes?: string | null
          status_updated_at?: string | null
          last_activity_at?: string | null
          status_history?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          user_phone?: string
          user_name?: string
          company_name?: string
          company_country?: string
          plan_coverage_summary?: string | null
          chat_summary?: string | null
          recent_messages?: Json | null
          status?: 'pending' | 'in_progress' | 'waiting_for_customer' | 'waiting_for_team' | 'resolved' | 'cancelled'
          requested_at?: string | null
          resolved_at?: string | null
          notes?: string | null
          gender?: string | null
          age?: number | null
          city?: string | null
          current_status?: 'pending' | 'reviewing_case' | 'contacting_customer' | 'working_on_solution' | 'discussion_with_team' | 'waiting_for_approval' | 'preparing_response' | 'resolved' | 'cancelled'
          status_message?: string | null
          assigned_to?: string | null
          internal_notes?: string | null
          customer_notes?: string | null
          status_updated_at?: string | null
          last_activity_at?: string | null
          status_history?: Json | null
        }
      }
    }
  }
}
